[General]
allow-wifi-access=false
bypass-tun=10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 239.255.255.250/32, 255.255.255.255/32
disable-stun=true
disconnect-on-policy-change=true
dns-server=119.29.29.29, 223.5.5.5
doh-server=https://223.5.5.5/resolve, https://sm2.doh.pub/dns-query
geoip-url=https://gitlab.com/Masaiki/GeoIP2-CN/-/raw/release/Country.mmdb
interface-mode=auto
ipv6=false
proxy-test-url=http://connectivitycheck.gstatic.com
resource-parser=https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Resource/Script/Sub-Store/sub-store-parser_for_loon.js
skip-proxy=192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com, e.crashlynatics.com
sni-sniffing=true
ssid-trigger="Ccccccc":DIRECT,"cellular":RULE,"default":RULE
switch-node-after-failure-times=3
test-timeout=2
wifi-access-http-port=7222
wifi-access-socks5-port=7221

[Proxy]
🇭🇰 Alibaba-HK-Games = Shadowsocks,8-210-6-182.lzmt.org,46521,aes-256-gcm,"Uy1nyf8aq7"
🇭🇰 Alibaba-HK-Lite = trojan,8-210-6-182.lzmt.org,64120,"YzvmAawlG7",tls-name=8-210-6-182.lzmt.org
🇭🇰 Alibaba-HK-Pro = trojan,dagebeidale.donghui.tech,27182,"YzvmAawlG7",tls-name=8-210-6-182.lzmt.org
🇭🇰 Azure-HK-Lite = trojan,20-189-74-44.lzmt.org,45437,"7p8YOmACSY",tls-name=20-189-74-44.lzmt.org
🇭🇰 Azure-HK-Pro = trojan,hncu.donghui.tech,24604,"7p8YOmACSY",tls-name=20-189-74-44.lzmt.org
🇺🇸 Contabo-US-Lite = trojan,85-239-235-232.lzmt.org,25484,"9awMqCokjg",tls-name=85-239-235-232.lzmt.org
🇺🇸 Contabo-US-Pro = trojan,hzcu.donghui.tech,50275,"9awMqCokjg",tls-name=85-239-235-232.lzmt.org
🇯🇵 ExtraVM-JP-Lite = trojan,103-214-71-16.lzmt.org,8800,"aGWl3RD9MQ",tls-name=103-214-71-16.lzmt.org
🇯🇵 ExtraVM-JP-Pro = trojan,hzyd.donghui.tech,21043,"aGWl3RD9MQ",tls-name=103-214-71-16.lzmt.org
🇩🇪 Koyeb-DE = vmess,considerable-rikki-gakiyukr.koyeb.app,443,chacha20-ietf-poly1305,"de04add9-5c68-8bab-950c-08cd5320df18",over-tls=true,tls-name=considerable-rikki-gakiyukr.koyeb.app,transport=ws,path=/vmess,host=considerable-rikki-gakiyukr.koyeb.app
🇯🇵 Koyeb-JP = vmess,aesthetic-norine-zfjbkkvsqu.koyeb.app,443,chacha20-ietf-poly1305,"de04add9-5c68-8bab-950c-08cd5320df18",over-tls=true,tls-name=aesthetic-norine-zfjbkkvsqu.koyeb.app,transport=ws,path=/vmess,host=aesthetic-norine-zfjbkkvsqu.koyeb.app
Netcup-AT-Lite = trojan,89-58-61-124.lzmt.org,22796,"s9TQKrCFtO"
Netcup-AT-Pro = trojan,hzcu.donghui.tech,38457,"s9TQKrCFtO",tls-name=89-58-61-124.lzmt.org

[Remote Proxy]

[Remote Filter]

[Proxy Group]
Proxies = select,Auto - UrlTest,DIRECT,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Domestic = select,DIRECT,Proxies
Scholar = select,DIRECT,Proxies,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Others = select,Proxies,DIRECT
AdBlock = select,REJECT,DIRECT,Proxies
Apple = select,DIRECT,Proxies
AsianTV = select,DIRECT,Proxies,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro
GlobalTV = select,Proxies,DIRECT,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Netflix = select,Proxies,DIRECT,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Spotify = select,Proxies,DIRECT,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Telegram = select,Proxies,DIRECT,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Steam = select,Proxies,DIRECT
Speedtest = select,Proxies,DIRECT,Domestic,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
PayPal = select,DIRECT,Proxies
Microsoft = select,Proxies,DIRECT
Netease Music = select,DIRECT,Proxies
Auto - UrlTest = url-test,🇭🇰 Alibaba-HK-Games,🇭🇰 Alibaba-HK-Lite,🇭🇰 Alibaba-HK-Pro,🇭🇰 Azure-HK-Lite,🇭🇰 Azure-HK-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro,url=http://cp.cloudflare.com/generate_204,interval=1800

[Rule]
GEOIP,CN,DIRECT
FINAL,Others

[Remote Rule]
https://raw.githubusercontent.com/tindy2013/subconverter/master/base/rules/LocalAreaNetwork.list,DIRECT
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Scholar.list,Scholar
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Reject.list,AdBlock
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Netflix.list,Netflix
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Spotify.list,Spotify
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Bilibili.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/IQIYI.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Letv.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/MOO.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Tencent%20Video.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Youku.list,AsianTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/ABC.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Abema%20TV.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Amazon.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Apple%20News.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Apple%20TV.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Bahamut.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/BBC%20iPlayer.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/DAZN.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Disney%20Plus.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/encoreTVB.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Fox%20Now.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Fox%2B.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/HBO%20Go.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/HBO%20Max.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Hulu%20Japan.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Hulu.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Japonx.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/JOOX.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/KKBOX.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Line%20TV.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/myTV%20SUPER.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Netflix.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Pandora.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/PBS.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Pornhub.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Soundcloud.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/ViuTV.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/YouTube%20Music.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/YouTube.list,GlobalTV
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Telegram.list,Telegram
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Steam.list,Steam
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Speedtest.list,Speedtest
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/PayPal.list,PayPal
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Microsoft.list,Microsoft
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Media/Netease%20Music.list,Netease Music
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Special.list,DIRECT
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Proxy.list,Proxies
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Domestic.list,Domestic
https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Apple.list,Apple

[Rewrite]

[Host]

[Script]
cron "16 9 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/duokan/duokan.js, tag=多看阅读
cron "17 9 * * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/flyertea/flyertea.js,tag=飞客茶馆
cron "18 9 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10010/10010.js, tag=中国联通
cron "19 9 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wanda/wanda.js, tag=万达电影
http-request ^https:\/\/user-api-prd-mx\.wandafilm\.com script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wanda/wanda.cookie.js, tag=万达电影_cookie
http-request ^https:\/\/www\.duokan\.com\/checkin\/v0\/status script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/duokan/duokan.cookie.js, requires-body=true, tag=多看_cookie
http-request ^https:\/\/www\.flyertea\.com\/source\/plugin\/mobile\/mobile\.php\?module=getdata&.* script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/flyertea/flyertea.cookie.js, tag=飞客茶馆_cookie
http-request ^https?:\/\/act.10010.com\/SigninApp(.*?)\/signin\/daySign script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10010/10010.cookie.js, tag=中国联通_cookie2
http-request ^https?:\/\/act.10010.com\/SigninApp\/signin\/querySigninActivity.htm script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10010/10010.cookie.js, tag=中国联通_cookie1
http-request ^https?:\/\/m.client.10010.com\/dailylottery\/static\/(textdl\/userLogin|active\/findActivityInfo) script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10010/10010.cookie.js, tag=中国联通_cookie3

[MITM]
ca-p12=MIIKGQIBAzCCCeMGCSqGSIb3DQEHAaCCCdQEggnQMIIJzDCCBBcGCSqGSIb3DQEHBqCCBAgwggQEAgEAMIID/QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQImj1O53xwYioCAggAgIID0HZE8LBl4XFV6NulqdzN58vwAkhwiiES++WDPqsE+NHCIa8VCBlfd6/MV21vO2zw8X90mSaO2/PEW7hyH6890zrF11J3rxDzkVtUnV7e8rq5vOdivjWl4s5Nx5zgyJ0AOHJU7Xe2f8OMb4VzsAqeqF/D6FwNGZBJhBn0nPCRFIIgEpOFUrcwvErPbySY6w8mmHm0DVbKvBFGqOth3fco6gIBpZBILgaQ8t9eLep3IiBFcyH1ezILwgOJ0G0qOJwRxOIXRYT3SaTD65rL90w2nW3xcD8jU5raF3PBDEpWf2+xis69nRU8QiWLjJEJkedE+GpZ/CEKR2BL02E9uB+IFF1/Y4bXk17Ty7D8D0WbIgKeLvRcKxFZoQEZfr/vEpdzedt704NBjDRPe3TPDApQgBtvXFvKZ9RB7uo17AJkLZbTGicFVP+a33+e0B1594zNy30eZ3zwwgpsdZ7S23JX/90FQwsTJWxpO4f9qaDqUHVcsSVlG21U4ujIPWkpIi51XE9gM+JmL6nWaU8cRY2CI0ETLnsSWIOJfQG4s6sy0P5liJfqVUtIpZqrSxdzmGlLe2HsOQYo+M6SVpwx8Liopqu5vrvZhuUlUAwmjDodianY57AObCYP5/fM/3yKeZW7v9JH0pQY9eQ5qT6+oWIWoxnERYbXqpEGUDWN6vUG/JkJ6paHIyJ07mCLs4hXXWCin3dAXzmwyMNyGPH3SH03EKK2o/aMWTQNSfSyzFSDS+xXrj3wAZLdzTlyLA4l0iZhzvWLcgfzqHaj922hFhuO3zxQr2cVQihMwXd0gCPsNA4b0Uqaor2GF3qHxctscIGyKafNpmsVM7pSvYmqi0lMijjVfYsx3zV4FgYfQBOQAEaD6VXIHHeg/JBDbfatoQOp6j+GW/Mz5djaeHarA6QdZVeKiGLkKOXT3JYLtxL8QUx2SINlLgWpR3XvMY7f8cIyPMsTrJdLix5wXVRtUVx2A83GyAOt3QxP/rtM+b+86YtAhBdSTRhJfuDL4sjW4//wtnU0B0CzpOlB1CXRprcnUSUeGyOD4eiOaBYnPpY5wUYyQ+eJYQvYdXWDiFx2sBSxyZMAiXMLtBxBoGoyirzFZKK3cw6DdjXrOGepcqFlesEzraz8yfXerOcPwgI4JD13oDKSiw3iUhjTnfrXpoAX+3rEhNfJeqFf7nooGd30z//v4u09KM3l2gEA9WJt60leoDkp3PjL8LPsgBjO5f+odey9O/YqHmxt3dpRD02HvL5VhnJG/kBeZpGd81yX0ceM8x5f2HKzMy38osE6Q/Ru+L0wggWtBgkqhkiG9w0BBwGgggWeBIIFmjCCBZYwggWSBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQIJsPUIRvXx3ACAggABIIEyJxMbTjKmMs37xEKKy5d8HBJzPs30yLXeSbO0taa3o6XGEGt6rbBIF3MIGSKAOLuLOwhddVqkFxdUkYiAUTMptSrN8YyR9yhn06mkZPViPHrKNMXIKlAomg87rD54e8AnQPxKvOVPUYne7WBu4QWrUnbuBTOnoWLQAY6dRRE4EDAdQbMRx34sWpjVBvNrgO1h36T11wnCIGDC+FNchV/zs0Xfpt+JB2HGe1KXxH2lO9QKo0ONQlx/GtKBto1HRyN0pzEbdifUBqy1hgVjb5KnK7z3ah3lcZITYQqprn85Mrc8sMfDJRWZlXJM4t4Tz27XbHIlGxnvSmSHGFl74yKbIGCgz/mr9LCwQt8HAeG5QR4+KpImehYGEZeqysAh1ywPTmWnojmdHrrjuUowPZPdihzKgONsiDgCHTRYzmAlDcPGNlipjIOacSC/hgf6lIZL/QelH8eC3lefpAbyE1paruw2a39yLRX4rb4DWcWk0n3dsy23PElhLBTwGQQsaHTbz7EIabEOb8/tPsOM9P/LaHrD3A3nODPvmgMyAdGsXJ+sHPTjFXOGn2vuB5edJvVARZnQZIpPskcDvcL/Ho+SEITaSYREm2iNkRya0jTBoQ7mtrR+DmE7plvWdjcDceOafDTs81rtrsJ5zdcxOHOmw4QTUtOiebnulbu6kChC5pddgVY9ahTSjQsnxJ5xkAn2AJeS/2GdmIV0edXdK0ojHxYgLWfDjv6WNZ3mag9+ntZw+m7dIwqLTQHPC+Q+YWJMHU8l8Mfu4vSAfG0k15GMjy40Pavi+6UdadTgKajm3N8ieCTyDoSsdf8HGUZkCNB2nAU2UhTwrCB/2APoKy7Mwg+DHIb6G5o9OCeA9ZmSov2dDsWrxTD6rlkjveGGfhIqvlotcpqKBMf752pj/qtCMJq1+SqcIWZEW20jL7AF5ZkEBNcDWkAaBAl1rvTqH8d6vjYQtQm3v9RD3z0cF/xu+og84O3OrKXp8vb3uTn7lOX42RsObEWKW7rBfvkiseSZH8QMzPcmy1oBt6R0mZlmqD/gOGN0V/ipkEY1+YGFmIkgvECziZjHOIvdeTKG09duCsbmm9lHIFcnRSNjVJC/z+ITpjzhh1LNPiKRGSu+pzMkO+nv6mKSXZRrZBI1suhidVSeISK5OqbH+EGYe5nQbG+8LEnWNyKPsMTZlG3v3RRKIi1Qe0blmqqISzfID+KmHjK1/aJIZP7QKhlfyGDfqlbl/hT3Pbxl85AI1iU4DeMrTbKfZgAHNExukebLZbZjumZ1PRKGruc5gIGFF9pc0QBt1O1DSNBoWCNiqsZWm1MlJ1o6sDKRZArHU2dvonkOfkk6h4wfHV2Pn2hBZnIubYvuOZ1vCfM9ghPeVGzilxhh2arerkC9E60VUJx1iMpPTfjU1uw94gA30GSrx2dWRo6HcP3gW9s/va/2NxrsjswVO9qEmOLLZS9BF+e2PQecncoDUsbbunZ8+sdtm/OXQOazWGS5W/Pl315yzH0o0bYcolAUWDYt1hPCFvwOAfxWNZFoTFYEw4dJUAYMGvaRdg3ywQ/jK2k1MOMv+gbHc8p/jpbHNVQQtbBIuwAsvICQNX6PCSDbCMS/K/AiKivnffQ8kSDMFX9ijGBkDAjBgkqhkiG9w0BCRUxFgQUlgCJh1d8WORIThv+Ju2NkD9fS0gwaQYJKoZIhvcNAQkUMVweWgBRAHUAYQBuAHQAdQBtAHUAbAB0ACAAQwBlAHIAdABpAGYAaQBjAGEAdABlACAARgBBADEAQQA5ADgANAA5ACAAKAAxADEAIABPAGMAdAAgADIAMAAxADkAKTAtMCEwCQYFKw4DAhoFAAQU8gunnEf1jIaelyXFamHM4uv0avgECFTS7nopsZ+Z
ca-passphrase=FA1A9849
hostname=m.client.10010.com, act.10010.com, www.flyertea.com, www.duokan.com, tieba.baidu.com
skip-server-cert-verify=false

