#!MANAGED-CONFIG https://api.v1.mk/sub?target=surge&ver=4&url=vmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIkFXUy1KUC1MaXRlIiwNCiAgImFkZCI6ICI0My4yMDcuMTcyLjI1MCIsDQogICJwb3J0IjogIjMwMTA3IiwNCiAgImlkIjogImFkNWQ4ZDA0LTlhZDQtNDUyZS1mOWM2LWQyMTZjOWI5MmViMiIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiLyIsDQogICJ0bHMiOiAibm9uZSIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ%3D%3D%7Ctrojan%3A%2F%2FjOdJ5zI24c%40tgbbhujmko521.southeastasia.cloudapp.azure.com%3A65402%3Fsecurity%3Dtls%26sni%3Dtgbbhujmko521.southeastasia.cloudapp.azure.com%26type%3Dtcp%26headerType%3Dnone%23Azure-SG-Lite%7Ctrojan%3A%2F%2FjOdJ5zI24c%40gddxb.073505.cn%3A17456%3Fsecurity%3Dtls%26sni%3Dtgbbhujmko521.southeastasia.cloudapp.azure.com%26type%3Dtcp%26headerType%3Dnone%23Azure-SG-Pro%7Ctrojan%3A%2F%2F9awMqCokjg%4085-239-235-232.lzmt.org%3A25477%3Fsecurity%3Dtls%26sni%3D85-239-235-232.lzmt.org%26type%3Dtcp%26headerType%3Dnone%23Contabo-US-Lite%7Ctrojan%3A%2F%2F9awMqCokjg%40shdx.073505.cn%3A50275%3Fsecurity%3Dtls%26sni%3D85-239-235-232.lzmt.org%26type%3Dtcp%26headerType%3Dnone%23Contabo-US-Pro%7Css%3A%2F%2FYWVzLTI1Ni1nY206ZG9raQ%3D%3D%4036.133.182.9%3A25557%23DMIT-HK-Pro%7Css%3A%2F%2FYWVzLTEyOC1nY206ZG9raWRva2k%3D%40120.233.45.130%3A28089%23Eons-HK-IEPL%7Css%3A%2F%2FYWVzLTEyOC1nY206ZG9raWRva2k%3D%40bgp.gg.bbcc.cyou%3A30683%23Eons-HK-IPLC%7Ctrojan%3A%2F%2FCrJHHyCSBL%40103.214.71.16%3A33377%3Fsecurity%3Dtls%26sni%3D103-214-71-16.lzmt.org%26type%3Dtcp%26headerType%3Dnone%23ExtraVM-JP-Lite%7Ctrojan%3A%2F%2FCrJHHyCSBL%40shshyd.073505.cn%3A21043%3Fsecurity%3Dtls%26sni%3D103-214-71-16.lzmt.org%26type%3Dtcp%26headerType%3Dnone%23ExtraVM-JP-Pro%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIktveWViLURFIiwNCiAgImFkZCI6ICJjb25zaWRlcmFibGUtcmlra2ktZ2FraXl1a3Iua295ZWIuYXBwIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImRlMDRhZGQ5LTVjNjgtOGJhYi05NTBjLTA4Y2Q1MzIwZGYxOCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiY29uc2lkZXJhYmxlLXJpa2tpLWdha2l5dWtyLmtveWViLmFwcCIsDQogICJwYXRoIjogIi92bWVzcyIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJjb25zaWRlcmFibGUtcmlra2ktZ2FraXl1a3Iua295ZWIuYXBwIiwNCiAgImFscG4iOiAiIg0KfQ%3D%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIktveWViLUpQIiwNCiAgImFkZCI6ICJhZXN0aGV0aWMtbm9yaW5lLXpmamJra3ZzcXUua295ZWIuYXBwIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImRlMDRhZGQ5LTVjNjgtOGJhYi05NTBjLTA4Y2Q1MzIwZGYxOCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiYWVzdGhldGljLW5vcmluZS16Zmpia2t2c3F1LmtveWViLmFwcCIsDQogICJwYXRoIjogIi92bWVzcyIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJhZXN0aGV0aWMtbm9yaW5lLXpmamJra3ZzcXUua295ZWIuYXBwIiwNCiAgImFscG4iOiAiIg0KfQ%3D%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIlRlbmNlbnQtVVMtTGl0ZSIsDQogICJhZGQiOiAiNDkuNTEuMjMyLjI0OCIsDQogICJwb3J0IjogIjMwMzA0IiwNCiAgImlkIjogImYzZmU4NzEwLTExZTAtNDNjZS1kNWRiLTQwYjVlNjIyMGFhNCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiLyIsDQogICJ0bHMiOiAibm9uZSIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ%3D%3D%7C&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5,218.30.19.40,61.134.1.4
external-controller-access = password@0.0.0.0:6170
http-api = password@0.0.0.0:6171
test-timeout = 5
http-api-web-dashboard = true
exclude-simple-hostnames = true
allow-wifi-access = true
http-listen = 0.0.0.0:6152
socks5-listen = 0.0.0.0:6153
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
🇯🇵 AWS-JP-Lite = vmess, 43.207.172.250, 30107, username=ad5d8d04-9ad4-452e-f9c6-d216c9b92eb2, tls=false, vmess-aead=true, ws=true, ws-path=/, sni=43.207.172.250, skip-cert-verify=false, tfo=false, udp-relay=false
🇸🇬 Azure-SG-Lite = trojan, tgbbhujmko521.southeastasia.cloudapp.azure.com, 65402, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com, skip-cert-verify=false, tfo=false, udp-relay=false
🇸🇬 Azure-SG-Pro = trojan, gddxb.073505.cn, 17456, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com, skip-cert-verify=false, tfo=false, udp-relay=false
🇺🇸 Contabo-US-Lite = trojan, 85-239-235-232.lzmt.org, 25477, password=9awMqCokjg, sni=85-239-235-232.lzmt.org, skip-cert-verify=false, tfo=false, udp-relay=false
🇺🇸 Contabo-US-Pro = trojan, shdx.073505.cn, 50275, password=9awMqCokjg, sni=85-239-235-232.lzmt.org, skip-cert-verify=false, tfo=false, udp-relay=false
🇭🇰 DMIT-HK-Pro = ss, 36.133.182.9, 25557, encrypt-method=aes-256-gcm, password=doki, tfo=false, udp-relay=false
🇭🇰 Eons-HK-IEPL = ss, 120.233.45.130, 28089, encrypt-method=aes-128-gcm, password=dokidoki, tfo=false, udp-relay=false
🇭🇰 Eons-HK-IPLC = ss, bgp.gg.bbcc.cyou, 30683, encrypt-method=aes-128-gcm, password=dokidoki, tfo=false, udp-relay=false
🇯🇵 ExtraVM-JP-Lite = trojan, 103.214.71.16, 33377, password=CrJHHyCSBL, sni=103-214-71-16.lzmt.org, skip-cert-verify=false, tfo=false, udp-relay=false
🇯🇵 ExtraVM-JP-Pro = trojan, shshyd.073505.cn, 21043, password=CrJHHyCSBL, sni=103-214-71-16.lzmt.org, skip-cert-verify=false, tfo=false, udp-relay=false
🇩🇪 Koyeb-DE = vmess, considerable-rikki-gakiyukr.koyeb.app, 443, username=de04add9-5c68-8bab-950c-08cd5320df18, tls=true, vmess-aead=true, tls13=false, ws=true, ws-path=/vmess, sni=considerable-rikki-gakiyukr.koyeb.app, ws-headers=Host:considerable-rikki-gakiyukr.koyeb.app, skip-cert-verify=false, tfo=false, udp-relay=false
🇯🇵 Koyeb-JP = vmess, aesthetic-norine-zfjbkkvsqu.koyeb.app, 443, username=de04add9-5c68-8bab-950c-08cd5320df18, tls=true, vmess-aead=true, tls13=false, ws=true, ws-path=/vmess, sni=aesthetic-norine-zfjbkkvsqu.koyeb.app, ws-headers=Host:aesthetic-norine-zfjbkkvsqu.koyeb.app, skip-cert-verify=false, tfo=false, udp-relay=false
🇺🇸 Tencent-US-Lite = vmess, 49.51.232.248, 30304, username=f3fe8710-11e0-43ce-d5db-40b5e6220aa4, tls=false, vmess-aead=true, ws=true, ws-path=/, sni=49.51.232.248, skip-cert-verify=false, tfo=false, udp-relay=false
🇨🇳 台湾节点 = direct
🇰🇷 韩国节点 = direct
🎥 奈飞节点 = direct

[Proxy Group]
🚀 节点选择 = select,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🚀 手动切换 = select,🇯🇵 AWS-JP-Lite,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇭🇰 DMIT-HK-Pro,🇭🇰 Eons-HK-IEPL,🇭🇰 Eons-HK-IPLC,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,🇺🇸 Tencent-US-Lite
📲 电报消息 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
💬 OpenAi = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📹 油管视频 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🎥 奈飞视频 = select,🎥 奈飞节点,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📺 巴哈姆特 = select,🇨🇳 台湾节点,🚀 节点选择,🚀 手动切换,DIRECT
📺 哔哩哔哩 = select,🎯 全球直连,🇨🇳 台湾节点,🇭🇰 香港节点
🌍 国外媒体 = select,🚀 节点选择,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🌏 国内媒体 = select,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🚀 手动切换
📢 谷歌FCM = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软Bing = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软云盘 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🍎 苹果服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎮 游戏平台 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎶 网易音乐 = select,DIRECT,🚀 节点选择
🎯 全球直连 = select,DIRECT,🚀 节点选择
🛑 广告拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换
🇭🇰 香港节点 = select,🇭🇰 DMIT-HK-Pro,🇭🇰 Eons-HK-IEPL,🇭🇰 Eons-HK-IPLC
🇯🇵 日本节点 = select,🇯🇵 AWS-JP-Lite,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇯🇵 Koyeb-JP
🇺🇲 美国节点 = select,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇺🇸 Tencent-US-Lite
🇸🇬 狮城节点 = select,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list,Ⓜ️ 微软Bing,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,Ⓜ️ 微软云盘,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报消息,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,💬 OpenAi,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,🎶 网易音乐,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,📹 油管视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,🎥 奈飞视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,📺 巴哈姆特,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,🚀 节点选择,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,🎯 全球直连,update-interval=86400
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼


