#!MANAGED-CONFIG https://www.shadowsocksr.link/config/servers/surge.yaml

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
🇭🇰 AperNet-HK-Games = ss, gzyda.073505.cn, 43328, encrypt-method=aes-256-gcm, password=VxvoQLCeXm
🇭🇰 AperNet-HK-Lite = trojan, 23-247-139-58.lzmt.org, 50311, password=mLgIX7VmRH, sni=23-247-139-58.lzmt.org
🇭🇰 AperNet-HK-Pro = trojan, gzyda.073505.cn, 61485, password=mLgIX7VmRH, sni=23-247-139-58.lzmt.org
🇸🇬 Azure-SG-Lite = trojan, tgbbhujmko521.southeastasia.cloudapp.azure.com, 50003, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com
🇸🇬 Azure-SG-Pro = trojan, gddxa.073505.cn, 17456, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com
🇺🇸 Contabo-US-Lite = trojan, 85-239-235-232.lzmt.org, 25484, password=9awMqCokjg, sni=85-239-235-232.lzmt.org
🇺🇸 Contabo-US-Pro = trojan, shdx.073505.cn, 50275, password=9awMqCokjg, sni=85-239-235-232.lzmt.org
🇯🇵 ExtraVM-JP-Lite = trojan, 103-214-71-16.lzmt.org, 8800, password=aGWl3RD9MQ, sni=103-214-71-16.lzmt.org
🇯🇵 ExtraVM-JP-Pro = trojan, shshcua.073505.cn, 21043, password=aGWl3RD9MQ, sni=103-214-71-16.lzmt.org
🇩🇪 Koyeb-DE = vmess, considerable-rikki-gakiyukr.koyeb.app, 443, username=de04add9-5c68-8bab-950c-08cd5320df18, tls=true, vmess-aead=true, ws=true, ws-path=/vmess, sni=considerable-rikki-gakiyukr.koyeb.app, ws-headers=Host:considerable-rikki-gakiyukr.koyeb.app
🇯🇵 Koyeb-JP = vmess, aesthetic-norine-zfjbkkvsqu.koyeb.app, 443, username=de04add9-5c68-8bab-950c-08cd5320df18, tls=true, vmess-aead=true, ws=true, ws-path=/vmess, sni=aesthetic-norine-zfjbkkvsqu.koyeb.app, ws-headers=Host:aesthetic-norine-zfjbkkvsqu.koyeb.app
Netcup-AT-Lite = trojan, 89-58-61-124.lzmt.org, 22796, password=s9TQKrCFtO
Netcup-AT-Pro = trojan, bjcu.073505.cn, 38457, password=s9TQKrCFtO, sni=89-58-61-124.lzmt.org

[Proxy Group]
🚀 节点选择 = select,♻️ 自动选择,DIRECT,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
♻️ 自动选择 = url-test,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🌍 国外媒体 = select,🚀 节点选择,♻️ 自动选择,🎯 全球直连,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
📲 电报信息 = select,🚀 节点选择,🎯 全球直连,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
Ⓜ️ 微软服务 = select,🎯 全球直连,🚀 节点选择,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
🍎 苹果服务 = select,🚀 节点选择,🎯 全球直连,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
📢 谷歌FCM = select,🚀 节点选择,🎯 全球直连,♻️ 自动选择,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro
🎯 全球直连 = select,DIRECT,🚀 节点选择,♻️ 自动选择
🛑 全球拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,🎯 全球直连,♻️ 自动选择,🇭🇰 AperNet-HK-Games,🇭🇰 AperNet-HK-Lite,🇭🇰 AperNet-HK-Pro,🇸🇬 Azure-SG-Lite,🇸🇬 Azure-SG-Pro,🇺🇸 Contabo-US-Lite,🇺🇸 Contabo-US-Pro,🇯🇵 ExtraVM-JP-Lite,🇯🇵 ExtraVM-JP-Pro,🇩🇪 Koyeb-DE,🇯🇵 Koyeb-JP,Netcup-AT-Lite,Netcup-AT-Pro

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 全球拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报信息,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list,🚀 节点选择,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连,update-interval=86400
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼

