[General]
allow-udp-proxy=false
bypass-tun=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server=system,119.29.29.29,223.5.5.5
host=127.0.0.1
skip-proxy=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com

[Proxy]
🇭🇰 Alibaba-HK = vmess,8.218.158.168,6665,chacha20-ietf-poly1305,"14ade852-509e-42f3-fcd7-837872db6ef1",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇸🇬 Alibaba-SG = vmess,47.236.20.150,19070,chacha20-ietf-poly1305,"0c13c13f-3beb-4028-bdad-24a48737f030",over-tls:false,transport:tcp,skip-cert-verify:0
🇯🇵 Awesomecloud-JP = vmess,154.93.3.5,16302,chacha20-ietf-poly1305,"1c819c5e-d85c-4f68-b6b2-57f43c5b7180",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇯🇵 Awesomecloud-JP 2 = vmess,154.93.3.250,48710,chacha20-ietf-poly1305,"396384c1-16f4-485b-e7fc-a78dfff7c3cf",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
AWS-AS = vmess,social.starkxstream.shop,36628,chacha20-ietf-poly1305,"c981af30-a03a-4fdc-b889-1425eb3ecc04",over-tls:true,tls-name:social.starkxstream.shop,transport:tcp,skip-cert-verify:0
🇦🇺 AWS-AU = vmess,13.236.232.142,443,chacha20-ietf-poly1305,"0cc17daa-f2ac-4449-e7c8-8d5b9d2bc007",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇦🇺 Azure-AU = vmess,20.213.250.56,59592,chacha20-ietf-poly1305,"2508416f-0db1-4a28-9236-ca81d669a51b",over-tls:false,transport:tcp,skip-cert-verify:0
🇭🇰 Azure-HK = vmess,20.2.66.98,65500,chacha20-ietf-poly1305,"6b2e381c-8214-47c7-aa73-54c803ef1d22",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇯🇵 Azure-JP = vmess,20.18.32.26,31736,chacha20-ietf-poly1305,"378d7f6a-dd87-4a3a-dad8-6382db444d7d",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇰🇷 Azure-KR = vmess,20.196.226.111,54032,chacha20-ietf-poly1305,"a4ac41c5-0e5c-43e7-88e8-0966dec36734",over-tls:false,transport:tcp,skip-cert-verify:0
🇯🇵 Linode-JP = Shadowsocks,172.104.87.35,65482,aes-256-gcm,"2XrfZTil8p"
🇰🇷 Ntte-KR = Shadowsocks,112.196.223.64,55128,aes-256-gcm,"15823asdLa"
🇦🇺 Oracle-AU = vmess,1253.heisigou.eu.org,2083,chacha20-ietf-poly1305,"3ed83f93-a70f-46fd-d44d-f03368bfd6be",over-tls:true,tls-name:1253.heisigou.eu.org,transport:ws,path:/ali,host:1253.heisigou.eu.org,skip-cert-verify:0
🇯🇵 Oracle-JP = vmess,138.2.62.108,43330,chacha20-ietf-poly1305,"7691c693-ddb6-41fb-808d-30243c3ec3a9",over-tls:false,transport:tcp,skip-cert-verify:0
🇯🇵 Oracle-JP 2 = vmess,64.110.103.245,33079,chacha20-ietf-poly1305,"17906350-6b0a-4623-b4cc-68e3e7469bf4",over-tls:false,transport:tcp,skip-cert-verify:0
🇯🇵 Oracle-JP-优选 = vmess,162.159.129.217,80,chacha20-ietf-poly1305,"a6824d8a-3112-4123-9344-798112b1a1c3",over-tls:false,transport:ws,path:/dsabhdsa,host:150-230-97-54.lzmt.org,skip-cert-verify:0
🇰🇷 Oracle-KR = vmess,152.70.89.135,59194,chacha20-ietf-poly1305,"58600d1a-e6e6-4d93-c291-13bed353563d",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
🇰🇷 Oracle-KR 2 = vmess,140.238.8.36,19220,chacha20-ietf-poly1305,"b4c91687-fae4-46db-bae5-c14e9bdaf04d",over-tls:false,transport:ws,path:/b4c91687,host:,skip-cert-verify:0
🇸🇬 Oracle-SG-优选 = vmess,162.159.129.217,80,chacha20-ietf-poly1305,"93447aef-58ae-45d0-be2a-2aa636c38072",over-tls:false,transport:ws,path:/sa,host:129-150-59-244.lzmt.org,skip-cert-verify:0
🇸🇬 Tencent-SG = vmess,43.134.173.48,37787,chacha20-ietf-poly1305,"9c0e8629-e25e-4e04-fb8b-64e81d3a60cc",over-tls:false,transport:tcp,skip-cert-verify:0
🇬🇧 M247-UK = vmess,45.90.140.150,27713,chacha20-ietf-poly1305,"02863ef6-28f0-4ab3-da74-d2561b1fafc2",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:0
Oracle-AE = vmess,193.123.82.177,49628,chacha20-ietf-poly1305,"4866c836-5adc-4b52-d408-c76142ceebdf",over-tls:false,transport:tcp,skip-cert-verify:0
🇫🇷 Oracle-FR = vmess,144.24.199.87,51986,chacha20-ietf-poly1305,"d1b5c4b7-95d1-42ea-d234-9105facb1eb5",over-tls:false,transport:tcp,skip-cert-verify:0
🇬🇧 Oracle-UK = vmess,130.162.180.96,37242,chacha20-ietf-poly1305,"4de3e1d2-fd6f-4253-b921-d0db9f32dabd",over-tls:false,transport:tcp,skip-cert-verify:0
🇺🇸 Digitalvirt-US = vmess,154.40.62.118,23157,chacha20-ietf-poly1305,"e7583efe-47ba-4140-a8f8-a7ca3776218a",over-tls:false,transport:ws,path:/hgugh6,host:,skip-cert-verify:0
🇺🇸 DMIT-US = vmess,174.136.207.179,44277,chacha20-ietf-poly1305,"cdff5c0a-2aa1-4174-8a52-05001dde8da8",over-tls:false,transport:tcp,skip-cert-verify:0
🇺🇸 DMIT-US 2 = vmess,65.75.192.98,443,chacha20-ietf-poly1305,"fb18aee0-ec3c-4990-f1fd-a92dbc712cdc",over-tls:false,transport:tcp,skip-cert-verify:0
🇺🇸 Olink-US = vmess,104.160.19.84,12362,chacha20-ietf-poly1305,"9b7bc233-ea07-4a6a-be3b-681578358bd6",over-tls:false,transport:tcp,skip-cert-verify:0
🇨🇦 Oracle-CA = vmess,155.248.227.34,35987,chacha20-ietf-poly1305,"20bf85b4-4703-47d1-fd8e-0fd3e158d8ff",over-tls:false,transport:tcp,skip-cert-verify:0
🇺🇸 Oracle-US = vmess,129.153.71.116,27652,chacha20-ietf-poly1305,"e7376974-6a95-43c6-e447-65b76498520f",over-tls:false,transport:tcp,skip-cert-verify:0

[Remote Proxy]

[Proxy Group]
🚀 节点选择 = select,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🚀 手动切换 = select,🇭🇰 Alibaba-HK,🇸🇬 Alibaba-SG,🇯🇵 Awesomecloud-JP,🇯🇵 Awesomecloud-JP 2,AWS-AS,🇦🇺 AWS-AU,🇦🇺 Azure-AU,🇭🇰 Azure-HK,🇯🇵 Azure-JP,🇰🇷 Azure-KR,🇯🇵 Linode-JP,🇰🇷 Ntte-KR,🇦🇺 Oracle-AU,🇯🇵 Oracle-JP,🇯🇵 Oracle-JP 2,🇯🇵 Oracle-JP-优选,🇰🇷 Oracle-KR,🇰🇷 Oracle-KR 2,🇸🇬 Oracle-SG-优选,🇸🇬 Tencent-SG,🇬🇧 M247-UK,Oracle-AE,🇫🇷 Oracle-FR,🇬🇧 Oracle-UK,🇺🇸 Digitalvirt-US,🇺🇸 DMIT-US,🇺🇸 DMIT-US 2,🇺🇸 Olink-US,🇨🇦 Oracle-CA,🇺🇸 Oracle-US
📲 电报消息 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
💬 OpenAi = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📹 油管视频 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🎥 奈飞视频 = select,🎥 奈飞节点,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📺 巴哈姆特 = select,🇨🇳 台湾节点,🚀 节点选择,🚀 手动切换,DIRECT
📺 哔哩哔哩 = select,🎯 全球直连,🇨🇳 台湾节点,🇭🇰 香港节点
🌍 国外媒体 = select,🚀 节点选择,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🌏 国内媒体 = select,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🚀 手动切换
📢 谷歌FCM = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软云盘 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🍎 苹果服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎮 游戏平台 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎶 网易音乐 = select,DIRECT,🚀 节点选择
🎯 全球直连 = select,DIRECT,🚀 节点选择
🛑 广告拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换
🇭🇰 香港节点 = select,🇭🇰 Alibaba-HK,🇭🇰 Azure-HK
🇯🇵 日本节点 = select,🇯🇵 Awesomecloud-JP,🇯🇵 Awesomecloud-JP 2,🇯🇵 Azure-JP,🇯🇵 Linode-JP,🇯🇵 Oracle-JP,🇯🇵 Oracle-JP 2,🇯🇵 Oracle-JP-优选
🇺🇲 美国节点 = select,🇺🇸 Digitalvirt-US,🇺🇸 DMIT-US,🇺🇸 DMIT-US 2,🇺🇸 Olink-US,🇺🇸 Oracle-US
🇸🇬 狮城节点 = select,🇸🇬 Alibaba-SG,🇸🇬 Oracle-SG-优选,🇸🇬 Tencent-SG
🇨🇳 台湾节点 = select,DIRECT
🇰🇷 韩国节点 = select,🇰🇷 Azure-KR,🇰🇷 Ntte-KR,🇰🇷 Oracle-KR,🇰🇷 Oracle-KR 2
🎥 奈飞节点 = select,DIRECT

[Rule]
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼

[Remote Rule]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 广告拦截
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,Ⓜ️ 微软云盘
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报消息
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,💬 OpenAi
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,🎶 网易音乐
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,🎮 游戏平台
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,🎮 游戏平台
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,🎮 游戏平台
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,🎮 游戏平台
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,🎮 游戏平台
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,📹 油管视频
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,🎥 奈飞视频
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,📺 巴哈姆特
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,📺 哔哩哔哩
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,📺 哔哩哔哩
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,🌏 国内媒体
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,🚀 节点选择
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,🎯 全球直连

[URL Rewrite]
enable=true
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[Remote Rewrite]
https://raw.githubusercontent.com/Loon0x00/LoonExampleConfig/master/Rewrite/AutoRewrite_Example.list,auto

[MITM]
enable=true
hostname=*.example.com,*.sample.com
skip-server-cert-verify=true

