#!MANAGED-CONFIG https://api.v1.mk/sub?config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&expand=true&fdn=false&insert=false&list=false&scv=false&target=surge&tfo=false&udp=false&url=ss%3A%2F%2FYWVzLTI1Ni1nY206aFdSeDFtMGhMYw%3D%3D%40dcq.showsion.shop%3A30905%23Akile-TW%7Ctrojan%3A%2F%2FjOdJ5zI24c%40dcq.showsion.shop%3A24843%3Fsecurity%3Dtls%26sni%3Dtgbbhujmko521.southeastasia.cloudapp.azure.com%26type%3Dtcp%26headerType%3Dnone%23Azure-SG%7Css%3A%2F%2FYWVzLTI1Ni1nY206Y0E2YXZkUjlJaw%3D%3D%40zoda.showsion.shop%3A24223%23Catxis-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206WHFyRkh4NkpsSQ%3D%3D%40aizai798.infois.top%3A17237%23Dodo-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206eUl3SkRDWTd1TQ%3D%3D%40dcq.showsion.shop%3A41336%23Eons-HK%7Css%3A%2F%2FYWVzLTI1Ni1nY206c25pdVJuOUhpZw%3D%3D%40zoda.showsion.shop%3A27040%23Eons-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206UHI0SjZDTGtKZA%3D%3D%40dcq.showsion.shop%3A10860%23Eons-SG%7Css%3A%2F%2FYWVzLTI1Ni1nY206bU1vRTRGME4wQg%3D%3D%40aizai798.infois.top%3A27945%23Gocodeit-CA%7Css%3A%2F%2FYWVzLTI1Ni1nY206Z1I5M2hUcFljcQ%3D%3D%40zoda.showsion.shop%3A44001%23Grupo%2520ZGH%2520SPA-CL%7Css%3A%2F%2FYWVzLTI1Ni1nY206OE1CYktjaWsxUQ%3D%3D%40zoda.showsion.shop%3A44002%23JJSpa-CL%7Css%3A%2F%2FYWVzLTI1Ni1nY206cElnZHRiUTE4cw%3D%3D%40zoda.showsion.shop%3A44003%23Markahost-TR%7Css%3A%2F%2FYWVzLTI1Ni1nY206Y01tV3hwTnRVSA%3D%3D%40zoda.showsion.shop%3A44004%23Misaka-US%7Css%3A%2F%2FYWVzLTI1Ni1nY206aFdSeDFtMGhMYw%3D%3D%40tw-1.ac.laowanxiang.com%3A14732%23Akile-TW%7Ctrojan%3A%2F%2FjOdJ5zI24c%40183.240.187.172%3A14732%3Fsecurity%3Dtls%26sni%3Dtgbbhujmko521.southeastasia.cloudapp.azure.com%26type%3Dtcp%26headerType%3Dnone%23Azure-SG%7Css%3A%2F%2FYWVzLTI1Ni1nY206Y0E2YXZkUjlJaw%3D%3D%40183.134.21.38%3A14732%23Catxis-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206eUl3SkRDWTd1TQ%3D%3D%40hk-2.ac.laowanxiang.com%3A14732%23Eons-HK%7Css%3A%2F%2FYWVzLTI1Ni1nY206c25pdVJuOUhpZw%3D%3D%40183.240.187.164%3A14732%23Eons-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206UHI0SjZDTGtKZA%3D%3D%40sg-1.ac.laowanxiang.com%3A14732%23Eons-SG%7C&ver=4&xudp=false interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5,218.30.19.40,61.134.1.4
external-controller-access = password@0.0.0.0:6170
http-api = password@0.0.0.0:6171
test-timeout = 5
http-api-web-dashboard = true
exclude-simple-hostnames = true
allow-wifi-access = true
http-listen = 0.0.0.0:6152
socks5-listen = 0.0.0.0:6153
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
🇹🇼 Akile-TW = ss, dcq.showsion.shop, 30905, encrypt-method=aes-256-gcm, password=hWRx1m0hLc, tfo=false, udp-relay=false
🇸🇬 Azure-SG = trojan, dcq.showsion.shop, 24843, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com, skip-cert-verify=false, tfo=false, udp-relay=false
🇯🇵 Catxis-JP = ss, zoda.showsion.shop, 24223, encrypt-method=aes-256-gcm, password=cA6avdR9Ik, tfo=false, udp-relay=false
🇯🇵 Dodo-JP = ss, aizai798.infois.top, 17237, encrypt-method=aes-256-gcm, password=XqrFHx6JlI, tfo=false, udp-relay=false
🇭🇰 Eons-HK = ss, dcq.showsion.shop, 41336, encrypt-method=aes-256-gcm, password=yIwJDCY7uM, tfo=false, udp-relay=false
🇯🇵 Eons-JP = ss, zoda.showsion.shop, 27040, encrypt-method=aes-256-gcm, password=sniuRn9Hig, tfo=false, udp-relay=false
🇸🇬 Eons-SG = ss, dcq.showsion.shop, 10860, encrypt-method=aes-256-gcm, password=Pr4J6CLkJd, tfo=false, udp-relay=false
🇨🇦 Gocodeit-CA = ss, aizai798.infois.top, 27945, encrypt-method=aes-256-gcm, password=mMoE4F0N0B, tfo=false, udp-relay=false
Grupo ZGH SPA-CL = ss, zoda.showsion.shop, 44001, encrypt-method=aes-256-gcm, password=gR93hTpYcq, tfo=false, udp-relay=false
JJSpa-CL = ss, zoda.showsion.shop, 44002, encrypt-method=aes-256-gcm, password=8MBbKcik1Q, tfo=false, udp-relay=false
Markahost-TR = ss, zoda.showsion.shop, 44003, encrypt-method=aes-256-gcm, password=pIgdtbQ18s, tfo=false, udp-relay=false
🇺🇸 Misaka-US = ss, zoda.showsion.shop, 44004, encrypt-method=aes-256-gcm, password=cMmWxpNtUH, tfo=false, udp-relay=false
🇹🇼 Akile-TW 2 = ss, tw-1.ac.laowanxiang.com, 14732, encrypt-method=aes-256-gcm, password=hWRx1m0hLc, tfo=false, udp-relay=false
🇸🇬 Azure-SG 2 = trojan, 183.240.187.172, 14732, password=jOdJ5zI24c, sni=tgbbhujmko521.southeastasia.cloudapp.azure.com, skip-cert-verify=false, tfo=false, udp-relay=false
🇯🇵 Catxis-JP 2 = ss, 183.134.21.38, 14732, encrypt-method=aes-256-gcm, password=cA6avdR9Ik, tfo=false, udp-relay=false
🇭🇰 Eons-HK 2 = ss, hk-2.ac.laowanxiang.com, 14732, encrypt-method=aes-256-gcm, password=yIwJDCY7uM, tfo=false, udp-relay=false
🇯🇵 Eons-JP 2 = ss, 183.240.187.164, 14732, encrypt-method=aes-256-gcm, password=sniuRn9Hig, tfo=false, udp-relay=false
🇸🇬 Eons-SG 2 = ss, sg-1.ac.laowanxiang.com, 14732, encrypt-method=aes-256-gcm, password=Pr4J6CLkJd, tfo=false, udp-relay=false
🇰🇷 韩国节点 = direct
🎥 奈飞节点 = direct

[Proxy Group]
🚀 节点选择 = select,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🚀 手动切换 = select,🇹🇼 Akile-TW,🇸🇬 Azure-SG,🇯🇵 Catxis-JP,🇯🇵 Dodo-JP,🇭🇰 Eons-HK,🇯🇵 Eons-JP,🇸🇬 Eons-SG,🇨🇦 Gocodeit-CA,Grupo ZGH SPA-CL,JJSpa-CL,Markahost-TR,🇺🇸 Misaka-US,🇹🇼 Akile-TW 2,🇸🇬 Azure-SG 2,🇯🇵 Catxis-JP 2,🇭🇰 Eons-HK 2,🇯🇵 Eons-JP 2,🇸🇬 Eons-SG 2
📲 电报消息 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
💬 OpenAi = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📹 油管视频 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🎥 奈飞视频 = select,🎥 奈飞节点,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📺 巴哈姆特 = select,🇨🇳 台湾节点,🚀 节点选择,🚀 手动切换,DIRECT
📺 哔哩哔哩 = select,🎯 全球直连,🇨🇳 台湾节点,🇭🇰 香港节点
🌍 国外媒体 = select,🚀 节点选择,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🌏 国内媒体 = select,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🚀 手动切换
📢 谷歌FCM = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软Bing = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软云盘 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🍎 苹果服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎮 游戏平台 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎶 网易音乐 = select,DIRECT,🚀 节点选择
🎯 全球直连 = select,DIRECT,🚀 节点选择
🛑 广告拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换
🇭🇰 香港节点 = select,🇭🇰 Eons-HK,🇭🇰 Eons-HK 2
🇯🇵 日本节点 = select,🇯🇵 Catxis-JP,🇯🇵 Dodo-JP,🇯🇵 Eons-JP,🇯🇵 Catxis-JP 2,🇯🇵 Eons-JP 2
🇺🇲 美国节点 = select,🇺🇸 Misaka-US
🇸🇬 狮城节点 = select,🇸🇬 Azure-SG,🇸🇬 Eons-SG,🇸🇬 Azure-SG 2,🇸🇬 Eons-SG 2
🇨🇳 台湾节点 = select,🇹🇼 Akile-TW,🇹🇼 Akile-TW 2

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list,Ⓜ️ 微软Bing,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,Ⓜ️ 微软云盘,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报消息,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,💬 OpenAi,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,🎶 网易音乐,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,📹 油管视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,🎥 奈飞视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,📺 巴哈姆特,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,🚀 节点选择,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,🎯 全球直连,update-interval=86400
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼


