#!MANAGED-CONFIG https://api.v1.mk/sub?target=surge&ver=4&url=ss%3A%2F%2FYWVzLTI1Ni1nY206bG9ydVh3SEpWdA%3D%3D%40111.38.37.15%3A26782%23Akile-TW%7Css%3A%2F%2FYWVzLTI1Ni1nY206ZFluYmVLTXBQZA%3D%3D%40183.233.187.244%3A27357%23DMIT-HK%7Css%3A%2F%2Fbm9uZTpkb3ViLmlv%40178.173.255.20%3A27093%23Eons-HK%7Css%3A%2F%2FYWVzLTI1Ni1nY206c25pdVJuOUhpZw%3D%3D%4036.139.239.208%3A46263%23Eons-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206UHI0SjZDTGtKZA%3D%3D%40111.38.37.15%3A25980%23Eons-SG%7Css%3A%2F%2FYWVzLTI1Ni1nY206bU1vRTRGME4wQg%3D%3D%40183.233.187.244%3A27951%23Gocodeit-CA%7Css%3A%2F%2FYWVzLTI1Ni1nY206OE1CYktjaWsxUQ%3D%3D%40200.14.81.180%3A53731%23JJSpa-CL%7Css%3A%2F%2FYWVzLTI1Ni1nY206cElnZHRiUTE4cw%3D%3D%40213.238.182.236%3A54780%23Markahost-TR%7Css%3A%2F%2FYWVzLTI1Ni1nY206bjFjM3VDcnVrcw%3D%3D%4058.242.130.170%3A26244%23Misaka-US%7Css%3A%2F%2FYWVzLTI1Ni1nY206QUd5ZkFUNzJnMQ%3D%3D%40209.146.125.194%3A45631%23NeroCloud-TW%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIk9yYWNsZS1KUCIsDQogICJhZGQiOiAiNjQuMTEwLjEwMy4yNDUiLA0KICAicG9ydCI6ICIzMzA3OSIsDQogICJpZCI6ICIxNzkwNjM1MC02YjBhLTQ2MjMtYjRjYy02OGUzZTc0NjliZjQiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIm5vbmUiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7C&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5,218.30.19.40,61.134.1.4
external-controller-access = password@0.0.0.0:6170
http-api = password@0.0.0.0:6171
test-timeout = 5
http-api-web-dashboard = true
exclude-simple-hostnames = true
allow-wifi-access = true
http-listen = 0.0.0.0:6152
socks5-listen = 0.0.0.0:6153
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
🇹🇼 Akile-TW = ss, 111.38.37.15, 26782, encrypt-method=aes-256-gcm, password=loruXwHJVt, tfo=false, udp-relay=false
🇭🇰 DMIT-HK = ss, 183.233.187.244, 27357, encrypt-method=aes-256-gcm, password=dYnbeKMpPd, tfo=false, udp-relay=false
🇭🇰 Eons-HK = ss, 178.173.255.20, 27093, encrypt-method=none, password=doub.io, tfo=false, udp-relay=false
🇯🇵 Eons-JP = ss, 36.139.239.208, 46263, encrypt-method=aes-256-gcm, password=sniuRn9Hig, tfo=false, udp-relay=false
🇸🇬 Eons-SG = ss, 111.38.37.15, 25980, encrypt-method=aes-256-gcm, password=Pr4J6CLkJd, tfo=false, udp-relay=false
🇨🇦 Gocodeit-CA = ss, 183.233.187.244, 27951, encrypt-method=aes-256-gcm, password=mMoE4F0N0B, tfo=false, udp-relay=false
JJSpa-CL = ss, 200.14.81.180, 53731, encrypt-method=aes-256-gcm, password=8MBbKcik1Q, tfo=false, udp-relay=false
Markahost-TR = ss, 213.238.182.236, 54780, encrypt-method=aes-256-gcm, password=pIgdtbQ18s, tfo=false, udp-relay=false
🇺🇸 Misaka-US = ss, 58.242.130.170, 26244, encrypt-method=aes-256-gcm, password=n1c3uCruks, tfo=false, udp-relay=false
🇹🇼 NeroCloud-TW = ss, 209.146.125.194, 45631, encrypt-method=aes-256-gcm, password=AGyfAT72g1, tfo=false, udp-relay=false
🇯🇵 Oracle-JP = vmess, 64.110.103.245, 33079, username=17906350-6b0a-4623-b4cc-68e3e7469bf4, tls=false, vmess-aead=true, skip-cert-verify=false, tfo=false, udp-relay=false
🇰🇷 韩国节点 = direct
🎥 奈飞节点 = direct

[Proxy Group]
🚀 节点选择 = select,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🚀 手动切换 = select,🇹🇼 Akile-TW,🇭🇰 DMIT-HK,🇭🇰 Eons-HK,🇯🇵 Eons-JP,🇸🇬 Eons-SG,🇨🇦 Gocodeit-CA,JJSpa-CL,Markahost-TR,🇺🇸 Misaka-US,🇹🇼 NeroCloud-TW,🇯🇵 Oracle-JP
📲 电报消息 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
💬 OpenAi = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📹 油管视频 = select,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🎥 奈飞视频 = select,🎥 奈飞节点,🚀 节点选择,🇸🇬 狮城节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
📺 巴哈姆特 = select,🇨🇳 台湾节点,🚀 节点选择,🚀 手动切换,DIRECT
📺 哔哩哔哩 = select,🎯 全球直连,🇨🇳 台湾节点,🇭🇰 香港节点
🌍 国外媒体 = select,🚀 节点选择,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换,DIRECT
🌏 国内媒体 = select,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🚀 手动切换
📢 谷歌FCM = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软Bing = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软云盘 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🍎 苹果服务 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎮 游戏平台 = select,DIRECT,🚀 节点选择,🇺🇲 美国节点,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇰🇷 韩国节点,🚀 手动切换
🎶 网易音乐 = select,DIRECT,🚀 节点选择
🎯 全球直连 = select,DIRECT,🚀 节点选择
🛑 广告拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,DIRECT,🇭🇰 香港节点,🇨🇳 台湾节点,🇸🇬 狮城节点,🇯🇵 日本节点,🇺🇲 美国节点,🇰🇷 韩国节点,🚀 手动切换
🇭🇰 香港节点 = select,🇭🇰 DMIT-HK,🇭🇰 Eons-HK
🇯🇵 日本节点 = select,🇯🇵 Eons-JP,🇯🇵 Oracle-JP
🇺🇲 美国节点 = select,🇺🇸 Misaka-US
🇸🇬 狮城节点 = select,🇸🇬 Eons-SG
🇨🇳 台湾节点 = select,🇹🇼 Akile-TW,🇹🇼 NeroCloud-TW

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list,Ⓜ️ 微软Bing,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,Ⓜ️ 微软云盘,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报消息,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,💬 OpenAi,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,🎶 网易音乐,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,🎮 游戏平台,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,📹 油管视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,🎥 奈飞视频,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,📺 巴哈姆特,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,📺 哔哩哔哩,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,🚀 节点选择,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,🎯 全球直连,update-interval=86400
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼